// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Core.Infrastructure.Persistence;

#nullable disable

namespace Platform.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714144947_AddGlobalTemplates")]
    partial class AddGlobalTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Core.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date")
                        .HasColumnName("installation_date");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ScheduledDeletionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_deletion_at");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_assets_category_id");

                    b.HasIndex("ScheduledDeletionAt")
                        .HasDatabaseName("ix_assets_scheduled_deletion_at");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_assets_unit_id");

                    b.HasIndex("TenantId", "CategoryId")
                        .HasDatabaseName("ix_assets_tenant_id_category_id");

                    b.HasIndex("TenantId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_tenant_id_tag");

                    b.HasIndex("TenantId", "UnitId")
                        .HasDatabaseName("ix_assets_tenant_id_unit_id");

                    b.ToTable("assets", "assets");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ScheduledDeletionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_deletion_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_asset_categories");

                    b.HasIndex("ScheduledDeletionAt")
                        .HasDatabaseName("ix_asset_categories_scheduled_deletion_at");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_categories_tenant_id_name");

                    b.ToTable("asset_categories", "assets");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.GlobalMaintenanceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("frequency");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TargetEquipmentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_equipment_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_global_maintenance_templates");

                    b.HasIndex("Jurisdiction")
                        .HasDatabaseName("ix_global_maintenance_templates_jurisdiction");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_global_maintenance_templates_name");

                    b.ToTable("global_maintenance_templates", "pmoc");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2a0e-4b9d-4f3a-9c7e-1d2a3b4c5d6e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Modelo base alinhado à Lei 13.589/2018, Resolução Anvisa RE 09 e inspeções elétricas da NR-10 para equipamentos de climatização.",
                            Frequency = "Monthly",
                            Jurisdiction = "BR",
                            Name = "PMOC Padrão ANVISA (RE 09) + NR-10",
                            TargetEquipmentType = "Ar Condicionado"
                        });
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.GlobalTemplateTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalMaintenanceTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_maintenance_template_id");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("input_type");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_global_template_tasks");

                    b.HasIndex("GlobalMaintenanceTemplateId", "Order")
                        .HasDatabaseName("ix_global_template_tasks_global_maintenance_template_id_order");

                    b.ToTable("global_template_tasks", "pmoc");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a2b3c4d-5e6f-4789-a012-3456789abc01"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GlobalMaintenanceTemplateId = new Guid("6f1c2a0e-4b9d-4f3a-9c7e-1d2a3b4c5d6e"),
                            InputType = "Image",
                            IsMandatory = true,
                            Order = 1,
                            Title = "Foto do Local de Instalação (Visão Geral do Ambiente)"
                        },
                        new
                        {
                            Id = new Guid("7a2b3c4d-5e6f-4789-a012-3456789abc02"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GlobalMaintenanceTemplateId = new Guid("6f1c2a0e-4b9d-4f3a-9c7e-1d2a3b4c5d6e"),
                            InputType = "Image",
                            IsMandatory = true,
                            Order = 2,
                            Title = "Foto Frontal do Equipamento (Evaporadora)"
                        },
                        new
                        {
                            Id = new Guid("7a2b3c4d-5e6f-4789-a012-3456789abc03"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GlobalMaintenanceTemplateId = new Guid("6f1c2a0e-4b9d-4f3a-9c7e-1d2a3b4c5d6e"),
                            InputType = "Image",
                            IsMandatory = true,
                            Order = 3,
                            Title = "Foto do Quadro Elétrico / Painel de Comando (NR-10)"
                        },
                        new
                        {
                            Id = new Guid("7a2b3c4d-5e6f-4789-a012-3456789abc04"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GlobalMaintenanceTemplateId = new Guid("6f1c2a0e-4b9d-4f3a-9c7e-1d2a3b4c5d6e"),
                            InputType = "Checkbox",
                            IsMandatory = true,
                            Order = 4,
                            Title = "Limpeza da bandeja de drenagem e serpentina"
                        },
                        new
                        {
                            Id = new Guid("7a2b3c4d-5e6f-4789-a012-3456789abc05"),
                            Configuration = "{\"unit\":\"A\"}",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GlobalMaintenanceTemplateId = new Guid("6f1c2a0e-4b9d-4f3a-9c7e-1d2a3b4c5d6e"),
                            InputType = "Number",
                            IsMandatory = true,
                            Order = 5,
                            Title = "Medição da Corrente de Operação (Compressor)"
                        },
                        new
                        {
                            Id = new Guid("7a2b3c4d-5e6f-4789-a012-3456789abc06"),
                            Configuration = "{\"options\":[\"Íntegro\",\"Danificado\",\"Inexistente\"]}",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GlobalMaintenanceTemplateId = new Guid("6f1c2a0e-4b9d-4f3a-9c7e-1d2a3b4c5d6e"),
                            InputType = "SingleChoice",
                            IsMandatory = true,
                            Order = 6,
                            Title = "Estado do isolamento térmico"
                        });
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_plans");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("ix_maintenance_plans_asset_category_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_maintenance_plans_unit_id");

                    b.HasIndex("TenantId", "AssetCategoryId")
                        .HasDatabaseName("ix_maintenance_plans_tenant_id_asset_category_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_maintenance_plans_tenant_id_name");

                    b.HasIndex("TenantId", "UnitId")
                        .HasDatabaseName("ix_maintenance_plans_tenant_id_unit_id");

                    b.ToTable("maintenance_plans", "pmoc");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("ModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_key");

                    b.ToTable("permissions", "core");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.PlanTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("input_type");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<Guid>("MaintenancePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_plan_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plan_tasks");

                    b.HasIndex("MaintenancePlanId")
                        .HasDatabaseName("ix_plan_tasks_maintenance_plan_id");

                    b.HasIndex("TenantId", "MaintenancePlanId", "Order")
                        .HasDatabaseName("ix_plan_tasks_tenant_id_maintenance_plan_id_order");

                    b.ToTable("plan_tasks", "pmoc");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_id_name");

                    b.ToTable("roles", "core");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", "core");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_tax_id");

                    b.ToTable("tenants", "core");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_units_tenant_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_units_tenant_id_name");

                    b.ToTable("units", "core");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("SupabaseAuthId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("supabase_auth_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("SupabaseAuthId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_supabase_auth_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.ToTable("users", "core");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "core");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MaintenancePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_plan_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_work_orders_asset_id");

                    b.HasIndex("MaintenancePlanId")
                        .HasDatabaseName("ix_work_orders_maintenance_plan_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_work_orders_tenant_id_status");

                    b.HasIndex("TenantId", "AssetId", "ScheduledDate")
                        .HasDatabaseName("ix_work_orders_tenant_id_asset_id_scheduled_date");

                    b.HasIndex("TenantId", "MaintenancePlanId", "AssetId", "ScheduledDate")
                        .HasDatabaseName("ix_work_orders_tenant_id_maintenance_plan_id_asset_id_schedule");

                    b.ToTable("work_orders", "os");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.WorkOrderTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("input_type");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("PlanTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_task_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_work_order_tasks");

                    b.HasIndex("PlanTaskId")
                        .HasDatabaseName("ix_work_order_tasks_plan_task_id");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_work_order_tasks_work_order_id");

                    b.HasIndex("TenantId", "WorkOrderId", "Order")
                        .HasDatabaseName("ix_work_order_tasks_tenant_id_work_order_id_order");

                    b.ToTable("work_order_tasks", "os");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assets_asset_categories_category_id");

                    b.HasOne("Platform.Core.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_units_unit_id");

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.GlobalTemplateTask", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.GlobalMaintenanceTemplate", "GlobalMaintenanceTemplate")
                        .WithMany("Tasks")
                        .HasForeignKey("GlobalMaintenanceTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_global_template_tasks_global_maintenance_templates_global_m");

                    b.Navigation("GlobalMaintenanceTemplate");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.MaintenancePlan", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.AssetCategory", "AssetCategory")
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_plans_asset_categories_asset_category_id");

                    b.HasOne("Platform.Core.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_plans_units_unit_id");

                    b.Navigation("AssetCategory");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.PlanTask", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany("Tasks")
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_tasks_maintenance_plans_maintenance_plan_id");

                    b.Navigation("MaintenancePlan");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Role", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roles_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Platform.Core.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Unit", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Units")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Platform.Core.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_assets_asset_id");

                    b.HasOne("Platform.Core.Domain.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany()
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_orders_maintenance_plans_maintenance_plan_id");

                    b.Navigation("Asset");

                    b.Navigation("MaintenancePlan");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.WorkOrderTask", b =>
                {
                    b.HasOne("Platform.Core.Domain.Entities.PlanTask", "PlanTask")
                        .WithMany()
                        .HasForeignKey("PlanTaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_order_tasks_plan_tasks_plan_task_id");

                    b.HasOne("Platform.Core.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_tasks_work_orders_work_order_id");

                    b.Navigation("PlanTask");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.AssetCategory", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.GlobalMaintenanceTemplate", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.MaintenancePlan", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Units");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Platform.Core.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
